### ISSUE TITLE
Message error

### ISSUE THREAD

**Issue by TonyLight** [oscarotero/form-manager#33]
Hi,

How can I redefine an error message?

```php
FormManager\Inputs\Email::$error_message = "foo";
```
I'm not sure that's correct...

And, other question, can you add a CSRF token?

**Comment by oscarotero** [comment]
Yes, by now this is the only way to change the error texts.

And about the CSRF token, you can implement it as you whish, because it's only a hidden input with a hash and a validator, for example:

```php
$form['token-CSRF'] = Field::hidden()->addValidator('csrf', function ($field) {
    return token_is_valid($field->val() ?: 'Token not valid!!';
});
```

**Comment by TonyLight** [comment]
Thank you for the quick response :-)
Will it soon be possible to handle error messages in an external file, for example?

**Comment by oscarotero** [comment]
The best way to do it should allow to change the error messages for each instance. So, two fields with "required" attribute could have different messages, but by now you only can to change it in a global way using these static variables.
To change them in an external file, you can create a file like this:
https://github.com/oscarotero/form-manager/blob/master/src/locales/en.php
and include it in your code.

**Comment by TonyLight** [comment]
Yes that's what I did for now, thank you! :-)
