### ISSUE TITLE
check witch button is submitted

### ISSUE THREAD

**Issue by vetsolution** [oscarotero/form-manager#40]
Hi
Thank you for your fast reply yesterday.

I do you have a method witch check if a sumbit button is clicked (like doctrine (symfony) form manager)? Because I don't see another way that request POST array.

Have a nice day.

**Comment by oscarotero** [comment]
Hi.
I don't understand your problem. The submit input has a name and value, like any other input, so you only have to check if you receive that value. You can, even, have more than one submit, with different values (using the choose container):

```php
$form = F::form()->add([
    'name' => F::text()->label('Your name'),
    'action' => F::choose([
        'save' => F::submit()->label('Save name'),
        'duplicate' => F::sumbit()->label('Duplicate name')
    ])
]);

$form->loadFromGlobals();

if ($form['action']->val() === 'save') {
   echo 'save value';
} else {
    echo 'duplicate';
}
```
