### ISSUE TITLE
Default values are lost after load call

### ISSUE THREAD

**Issue by eusonlito** [oscarotero/form-manager#42]
I have this definition:

```php
$form = new FormManager\Containers\Form;

$form->add([
    'action' => F::hidden()->val('edit'),
    'id' => F::hidden()
]);
```

Then, I load a default value to `id`:

```php
$form->load(['id' => 1]);
```

After that, I lost `action` value:

```php
var_dump($form['action']);
```

```php
Hidden {#183 ▼
  +input: Input {#184 ▼
    #name: "input"
    #parent: Form {#180 ▶}
    #close: null
    #attributes: array:2 [▼
      "type" => "hidden"
      "value" => ""
    ]
    #data: []
    #vars: []
    #html: null
    #sanitizer: null
    #validators: []
    #error: null
    #key: "action"
  }
  #labelPosition: 0
  #render: null
  #rendering: false
}
```

**Comment by oscarotero** [comment]
This is not an issue, is the way the form must to work. The load method does not merge the old values with the newest. If you want to merge it (for any reason) you can do it by yourself:
```php
$values = $form->val();
$values = array_merge($values, $new_values);
$form->load($values);
```

But note that some inputs can have unespected values. For example, with inputs with the attribute `multiple`, collections or collectionMultiple containers, each time you merge the new values, they are appended to older, not replace them.

**Comment by eusonlito** [comment]
Ok, then was changed from `v4.2`? On previous versions were working with this same code. Thanks.

**Comment by oscarotero** [comment]
Yes, it was a bug, not a feature :smiley_cat:
