### ISSUE TITLE
Why Number validator extends Url validator?

### ISSUE THREAD

**Issue by eusonlito** [oscarotero/form-manager#43]
https://github.com/oscarotero/form-manager/blob/master/src/Validators/Number.php#L4

**Comment by oscarotero** [comment]
Because they use the same method to check the value: [filter_var](http://php.net/filter_var), so this avoid code duplication (https://github.com/oscarotero/form-manager/blob/master/src/Validators/Url.php#L24)

**Comment by eusonlito** [comment]
And a trait solution with this validation function?

**Comment by oscarotero** [comment]
Maybe, but it's a very simple case, I don't see much benefit.

**Comment by eusonlito** [comment]
Because is not easy to remember that `Number` extends `Url` and on future you could make changes on `Url` that affect to `Number`.
