### ISSUE TITLE
How I can clear previous "select" options

### ISSUE THREAD

**Issue by eusonlito** [oscarotero/form-manager#45]
I need to clear the current options with new options (differents). How can I do it?

There are some `empty` method like jQuery?

My example:

```php
$form['states_id']->options([1 => 'aaaa']);

... very long process ...

$form['states_id']->options([2 => 'bbbb']);
```

After last step, $form['status_id'] has first and second assignment, but I need to clear first options without define again or other field redefinitions. Something like:

```php
$form['states_id']->options([1 => 'aaaa']);

... very long process ...

$form['states_id']->empty()->options([2 => 'bbbb']);
```

Thanks :)

**Comment by oscarotero** [comment]
There is not an `empty()` method, but it's good idea. I'm going to implement it.

**Comment by oscarotero** [comment]
Implemented `clear()` (php doesn't allow to create methods called "empty")

**Comment by eusonlito** [comment]
:+1:
