### ISSUE TITLE
Builder::addFactory should accept FactoryInterface

### ISSUE THREAD

**Issue by heneke** [oscarotero/form-manager#52]
Currently, Builder::addFactory does only accept objects of type Factory as opposed to the readme which states that custom factories have to implement FactoryInterface. Adding a FactoryInterface object to the Builder is not possible atm.

**Comment by oscarotero** [comment]
Hi, @heneke 
You're right. Fixed in the next patch released.
Thank you

**Comment by heneke** [comment]
Thanks :+1:
