### ISSUE TITLE
More flexibility in error label

### ISSUE THREAD

**Issue by cmoralesweb** [oscarotero/form-manager#53]
Validation errors are generated like this:

```
<label class="error" for="fm-input-32">The min value allowed is 1900</label>
``` 

The error class can't be customized, but it would be a nice feature :)

**Comment by oscarotero** [comment]
The error class can be customized in the render, but in the new version (4.4.0) you can customize it before the render, in the same way than the main label:
```php
$input->errorLabel->class('my-error-class');
```
