### ISSUE TITLE
Static method usage

### ISSUE THREAD

**Issue by airways** [oscarotero/form-manager#59]
Typically static method usage makes unit testing more difficult. I suggest removing the requirement for static usage, if possible.

**Comment by oscarotero** [comment]
The static methods is used only to instantiate Field classes, for example `F::text()` instead `new FormManager\Fields\Text()`, so I don't know how this can complicate unit testing.

**Comment by oscarotero** [comment]
In the [release 4.7](https://github.com/oscarotero/form-manager/releases/tag/4.7.0) you can use static methods or create builder instances.
