### ISSUE TITLE
Select 'placeholder'

### ISSUE THREAD

**Issue by rophini** [oscarotero/form-manager#65]
Is there a possibility to add a "placeholder" (e.g. '-- Please Select -- ') option to a select element?
It should generate something like this:

<option value="" disabled="disabled" selected="selected">-- Please Select --</option>

Thanks!

**Comment by oscarotero** [comment]
Yep, just add the placeholder like any other option:

```php
$select = F::select([
    '' => '-- Please Select --',
    1 => 'One',
    2 => 'Two',
]);
```
