### ISSUE TITLE
Allow any value into a select

### ISSUE THREAD

**Issue by eusonlito** [oscarotero/form-manager#71]
There are anyway to allow any value into a select?

I'm using select2 with ajax to load options from the plugin search and result values are not into original select options, then the form-manager validator trigger an error.

There are some parameter as `skipValidate` to disable validation?

Regards!

**Comment by oscarotero** [comment]
Yes:

```php
$select->allowNewValues(true)
```

**Comment by eusonlito** [comment]
![](https://i.giphy.com/VRuxlH7dZifN6.gif)
