### ISSUE TITLE
Select with attributes multiple and required throws a PHP error

### ISSUE THREAD

**Issue by eusonlito** [oscarotero/form-manager#74]
I have this code working without problems:

```php
'user_ids' => B::select()->attr([
    'multiple' => true,
])->allowNewValues(true)->label('Users'),
```

but adding `required` attribute:

```php
'user_ids' => B::select()->attr([
    'multiple' => true,
    'required' => true,
])->allowNewValues(true)->label('Users'),
```

generate a PHP error:

> [/vendor/form-manager/form-manager/src/Validators/Required.php - 34] strlen() expects parameter 1 to be string, array given

Thanks!

**Comment by oscarotero** [comment]
Thanks for the PR. [v5.1.3](https://github.com/oscarotero/form-manager/releases/tag/v5.1.3) released including your fix.
