### ISSUE TITLE
How to add additional parameters inside input / select

### ISSUE THREAD

**Issue by ysguy** [oscarotero/form-manager#77]
I would like to add some additional parameters inside my select statement. Essentially i want to make this

`<select id="companylist" class="selectpicker" name="companylist" aria-labelledby="fm-1" tabindex="-98"></select>`

look like this

<select id="companylist" class="selectpicker" name="companylist" aria-labelledby="fm-1" tabindex="-98" **data-live-search="true"**>

Note the addition of the 
`data-live-search="true"`

I tried a few things and couldn't grasp how to add this. 

Additionally (bonus points), please explain if there is a way to do the same for the sub <option></option> elements? i.e. <option **custom="value"**></option>

**Comment by oscarotero** [comment]
To add `data-*` attributes, you can use the `->data()` function:

```php
$select = F::select()->data(['live-search' => true);
```

For any other attribute, you can use the `->attr()` function or simply call a method named like the attribute name:

```php
//these lines are equivalent:
$select = F::select()->custom('value');
$select = F::select()->attr('custom', 'value');
$select = F::select()->attr(['custom' => 'value']);
```

To add extra attributes to the `<option>`, you need to create the option instead a plain array:

```php
$select = F::select()
    ->options([
       F::option()->custom('value'),
       F::option()->custom('value2')
    ]);
```

**Comment by ysguy** [comment]
For the data item i am getting an error, i see there is a single square bracket to start and no close. Unsure how that should work?
