### ISSUE TITLE
Validation of number inputs with decimal step

### ISSUE THREAD

**Issue by D-Heap** [oscarotero/form-manager#87]
https://github.com/oscarotero/form-manager/blob/fb530fdbf0c23cf8cefc9ce180a75cd1d7c575eb/src/Validators/Step.php#L26

The modulo validation fails for input of type number with decimal step (e.g. 0.1).
Using the `fmod()` method would fix the issue.

`if (fmod($input, $step)) { ... }`

**Comment by oscarotero** [comment]
Thanks for reporting this.
I've fixed and released the 6.1.0 version.
