### ISSUE TITLE
Optgroup not working in 6.1.0

### ISSUE THREAD

**Issue by psaikali** [oscarotero/form-manager#88]
First, thank you for this library, it's saved me countless hours of coding! Great job.

### Issue
I've been using 6.0.0 for a while and generating `<select>` fields with `<optgroup>` in them. But after updating to 6.1.0 a few days ago, the HTML output for these fields is broken and optgroups no longer work.

### Code used
```
$fields['test'] = Form::select(
	__( 'Test select  with optgroup', 'mbt' ),
	[
		'First optgroup' => [
			'option1_1' => 'First option',
			'option1_2' => 'Second option',
		],
		'Another optgroup' => [
			'option2_1' => 'Another first option',
			'option2_2' => 'Another second option',
			'option2_3' => 'Third option',
		],
	],
	[
		'name'      => 'optgroup_field',
		'id'        => 'optgroup_field',
	]
);
```

### Before/After
**6.0.0:**
![Capture 2020-11-29 à 09 48 59](https://user-images.githubusercontent.com/1606655/100537616-2a064000-322a-11eb-8744-4f5471c6366b.jpg)

**6.1.0:**
![Capture 2020-11-29 à 09 49 15](https://user-images.githubusercontent.com/1606655/100537693-de07cb00-322a-11eb-9408-b3a923f11657.jpg)

In the screenshot below, you can see the expected working version (6.0.0) at the top, and the buggy HTML output generated with 6.1.0:
![Capture 2020-11-29 à 10 06 56](https://user-images.githubusercontent.com/1606655/100537707-02fc3e00-322b-11eb-854e-7871b6127bc3.jpg)

Has the syntax changed since 6.1.0 for using optgroup in select fields?

Thank you for your help.

**Comment by oscarotero** [comment]
Hi.
Yes, there was a little change in the API in 6.1.0, sorry.

In 6.0.0, the only way to create options is with an array with `[value => label]`. This makes impossible to assign other attributes to a option (like id, data-*, class, etc..). So in 6.1.0, options can be defined as arrays, in order to assign any attribute. For example:

```php
Form::select('select one option', [
    'option_1' => 'First option',
    'option_2' => [
        'label' => 'Second option',
        'id' => 'option_2'
    ]
]
```

To assign optgroups to selects, datalist, etc you have the function `setOptgroups`, taking your example:

```php
$fields['test'] = Form::select(
    __( 'Test select  with optgroup', 'mbt' ),
    [],
    [
        'name'      => 'optgroup_field',
        'id'        => 'optgroup_field',
    ]
)->setOptgroups(
	[
		'First optgroup' => [
			'option1_1' => 'First option',
			'option1_2' => 'Second option',
		],
		'Another optgroup' => [
			'option2_1' => 'Another first option',
			'option2_2' => 'Another second option',
			'option2_3' => 'Third option',
		],
	],
);
```

**Comment by psaikali** [comment]
Awesome, thanks @oscarotero :)
