### ISSUE TITLE
6.1.0  version break compatibility with Select optgroups handling

### ISSUE THREAD

**Issue by Hubbitus** [oscarotero/form-manager#89]
In version 6.0.1 if you have in form:
```php
		F::select(
			'TestSelect',
			 [
				'Group1' => ['1' => 'one', '2' => 'two' ],
				'Group2' => ['1' => 'one', '2' => 'two' ],
				'Group3' => ['1' => 'one', '2' => 'two' ]
			]
			,[ 'id' => 'county', 'multiple' => 'multiple', 'class' => 'select2' ]
		),
```
you will got select with optgroups like:
![image](https://user-images.githubusercontent.com/720349/104134183-26251c00-5399-11eb-91bd-d35dc700e93d.png)

But in version 6.1 there was no any erros, but select will look like (got only groups):
![image](https://user-images.githubusercontent.com/720349/104134205-43f28100-5399-11eb-966b-00af93470237.png)

If such breaking chenge made intentionally there should be check and exception with hint how developer must adjust their code.
But really it is is bug on my mind. There was no any deprecation in `Select` interface, so breaking change should not be happened in stable versions (e.g. 6.*).

**Comment by Hubbitus** [comment]
Meantime code now should be re-written like:
```php
		'filter_county' => F::select(
			'TestSelect'
			,[]
			,[ 'id' => 'county', 'multiple' => 'multiple', 'class' => 'select2' ]
			)->setOptGroups([
				'Group1' => ['1' => 'one', '2' => 'two' ],
				'Group2' => ['1' => 'one', '2' => 'two' ],
				'Group3' => ['1' => 'one', '2' => 'two' ]
			]),
```
which is much less readable on my mind...

**Comment by Hubbitus** [comment]
Furthermore, in that setup it looks impossible turn it into array values, after form submit result in GET or POST will be like:
`filter_county=5&filter_county=7` instead of `filter_county[]=5&filter_county[]=7`.

**Comment by oscarotero** [comment]
Yes, the way to add optgroups has changed, here you have more information: https://github.com/oscarotero/form-manager/issues/88

**Comment by oscarotero** [comment]
And about the `multiple` attribute, yes, it's a bug. I just fixed it and release 6.1.1. Thanks for warning.

**Comment by Hubbitus** [comment]
> Yes, the way to add optgroups has changed, here you have more information: #88

But that should not happen in stable releases if you sue semantic versioning!??

**Comment by Hubbitus** [comment]
And thanks to fixing multiple values handling.

**Comment by oscarotero** [comment]
> But that should not happen in stable releases if you sue semantic versioning!??

Yes, you're right. My fault.
